### ISSUE TITLE
sklearn is missing in requirements

### ISSUE THREAD

**Issue by asobolev** [neuroneuro15/ratcave#1]
/usr/local/lib/python2.7/dist-packages/ratcave-0.5-py2.7-linux-x86_64.egg/ratcave/utils/orienting.py in <module>()
      2 
      3 import numpy as np
----> 4 from sklearn.decomposition import PCA
      5 from .. import _transformations as transformations
      6 

ImportError: No module named sklearn.decomposition

**Comment by neuroneuro15** [comment]
Thanks.  Actually, the rotate_to_var() function that uses sklearn shouldn't even be in ratcave anymore, as it is used only for vr of objects related to the Optitrack sytem.  I'll remove it this week.

**Comment by asobolev** [comment]
Cool! Thanks

**Comment by neuroneuro15** [comment]
Okay, it took more than a week, but it's removed!
