### ISSUE TITLE
Pyglet OBJ monkey example slow loading

### ISSUE THREAD

**Issue by stuaxo** [neuroneuro15/ratcave#9]
I've tried starting this in CPython and Pypy, either way it takes about 10 seconds from the window showing up to displaying the monkey.

**Comment by neuroneuro15** [comment]
Thank you for bringing this to my attention!  I've improved performance considerably now, and now get rendering of 25 monkeys in less than a second.  

It can certainly get faster, of course.  If we get more performance requests, I'll implement a profiling suite as part of testing.

**Comment by stuaxo** [comment]
Great!  This is much better.    Not sure if I will use ratcave (though it does seem pretty nice) in the end as I tend to go for slightly more liberal licenses than the GPL (and certainly won't ask you to change from License).

I noticed a rouge ```.``` seems to have snuck into tutorial2.py at line21.

I had a bit of trouble running the demos in pypy this time, this will probably work with numpypy instead of pypy, but I think their long term plan is to drop numpypy and have numpy work anyway.

**Comment by neuroneuro15** [comment]
Thanks!  Actually, I'm considering changing to the MIT license, so no 
worries there.  And thanks for the bug report.

Best wishes,

Nick
